{% set name = "pysox" %}
{% set version = "1.4.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

build:
  noarch: generic
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy >=1.9.0
    - pip
    - python
  run:
    - numpy >=1.9.0
    - python

test:
  imports:
    - sox

about:
  home: "https://github.com/rabitt/pysox"
  license: BSD-3-Clause
  license_family: BSD
  license_file: 
  summary: "Python wrapper around SoX."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - luiz-monad
